// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW0nQ6MsZdyJIehu5XtsVrqIqKDTg1pjQ',
    appId: '1:414432687968:web:9870265f268fa856911005',
    messagingSenderId: '414432687968',
    projectId: 'bomberos-1866b',
    authDomain: 'bomberos-1866b.firebaseapp.com',
    storageBucket: 'bomberos-1866b.firebasestorage.app',
    measurementId: 'G-6H22NY4EPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4XWhH-eThiSdGHILsxaMrEbAlbt1HHVM',
    appId: '1:414432687968:android:c514161e8e421117911005',
    messagingSenderId: '414432687968',
    projectId: 'bomberos-1866b',
    storageBucket: 'bomberos-1866b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-zGJlxT-ZRuWGYq7xv6jOglJgzc6I75M',
    appId: '1:414432687968:ios:bed9291efc5b36ee911005',
    messagingSenderId: '414432687968',
    projectId: 'bomberos-1866b',
    storageBucket: 'bomberos-1866b.firebasestorage.app',
    iosBundleId: 'com.example.proyectoIntegradorBomberos',
  );
}
